// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FileFilter {
    "name": string;
    "extensions": string[];

    /** Creates a new FileFilter instance. */
    constructor($$source: Partial<FileFilter> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("extensions" in $$source)) {
            this["extensions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): FileFilter {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField1_0($$parsedSource["extensions"]);
        }
        return new FileFilter($$parsedSource as Partial<FileFilter>);
    }
}

export class SaveFileRequest {
    "filename": string;
    "data": string;
    "isBinary": boolean;
    "filters": FileFilter[];

    /** Creates a new SaveFileRequest instance. */
    constructor($$source: Partial<SaveFileRequest> = {}) {
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }
        if (!("isBinary" in $$source)) {
            this["isBinary"] = false;
        }
        if (!("filters" in $$source)) {
            this["filters"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveFileRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SaveFileRequest {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filters" in $$parsedSource) {
            $$parsedSource["filters"] = $$createField3_0($$parsedSource["filters"]);
        }
        return new SaveFileRequest($$parsedSource as Partial<SaveFileRequest>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = FileFilter.createFrom;
const $$createType2 = $Create.Array($$createType1);
